### ISSUE TITLE
Hangs when run from `concurrently`

### ISSUE THREAD

**Issue by argv-minus-one** [cheddarbread/sheetloaf#18]
When `sheetloaf` is run using [`concurrently`](https://www.npmjs.com/package/concurrently), it hangs. It doesn't hang if run using `concurrently --raw`. It also doesn't hang if [the `!process.stdin.isTTY` code path](https://github.com/cheddarbread/sheetloaf/blob/c7b4ebcdee5c24ea11a7af3a42e6790b77e1d61e/index.js#L65-L75) is commented out.

See [this minimal reproducing example.](https://github.com/cheddarbread/sheetloaf/files/6889030/hang.zip) To demonstrate the problem:

1. Unpack the zip file.
2. Run `npm install`.
3. Run `npm run fail`. It will hang.
4. Run `npm run ok`. It won't hang.

**Comment by argv-minus-one** [comment]
Thanks for making this, by the way! Now that [Gulp is basically dead](https://github.com/gulpjs/gulp/issues/2536), there doesn't seem to be any other straightforward way to pipe Sass output through PostCSS.

**Comment by probablynotben** [comment]
Thank you for the detailed report! I was able to reproduce with the files provided.

You're right that commenting out the if statement. Looks like I'll have to be a bit smarter about detecting whether a pipe is actually being used or not.
